name: Kontrafei
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22671
title: Kontrafei
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#847f76'
    - '#05060e'
    - '#2c3713'
    - '#d8c1b6'
    - '#424968'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
