name: Kontrafei
favicon: null
layout_spectrum: 0.5493352136109024
typography_spectrum: 0.13804541365243495
title: Kontrafei Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#484848'
    - '#292829'
    - '#808080'
    - '#b8b8b8'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
