typography_spectrum: 0.22671
color:
  brandColors:
    - '#847f76'
    - '#05060e'
    - '#2c3713'
    - '#d8c1b6'
    - '#424968'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Kontrafei
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Kontrafei
purpose: []
