name: Kontrafei
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22671
title: Kontrafei
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#3c241a'
    - '#5a3d2a'
    - '#a47455'
    - '#8d6045'
  brandStrength: 1
  lightness: 0
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
